CREATE TABLE IF NOT EXISTS settlements (
  id UUID PRIMARY KEY,
  market_id UUID NOT NULL UNIQUE REFERENCES markets(id) ON DELETE CASCADE,
  outcome DOUBLE PRECISION NOT NULL,
  decided_at TIMESTAMPTZ NOT NULL DEFAULT now()
);